version: '3.8'

services:
  agent:
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
